# Generated by Django 5.2.6 on 2025-09-15 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendquery',
            name='user',
        ),
        migrations.AddField(
            model_name='trendquery',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='trend_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
