# Generated by Django 5.2.6 on 2025-09-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_remove_trendquery_user_trendquery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendresult',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
