# Generated by Django 5.2.6 on 2025-09-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_trendresult_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_emails',
            field=models.BooleanField(default=True),
        ),
    ]
