# Generated by Django 5.2.6 on 2025-09-17 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_user_wants_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wants_emails', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='trends.trendquery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'query')},
            },
        ),
    ]
