# Generated by Django 5.2.6 on 2025-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_querysubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wants_emails',
        ),
        migrations.AddField(
            model_name='querysubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
