# Generated by Django 5.2.6 on 2025-09-26 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0006_remove_user_wants_emails_querysubscription_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(default='signup', max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'created_at'], name='trends_sign_email_adff76_idx')],
            },
        ),
    ]
